FROM golang:1.25 AS build
WORKDIR /src

COPY go.mod ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -trimpath -ldflags="-s -w" -o /out/profile-api ./cmd/api

FROM gcr.io/distroless/static-debian12:nonroot
WORKDIR /
COPY --from=build /out/profile-api /profile-api
EXPOSE 8081
USER nonroot:nonroot
ENTRYPOINT ["/profile-api"]

